### ISSUE TITLE
Material sobre Python.

### ISSUE THREAD

**Issue by delete** [mazulo/django_groups_-_initial_steps#2]
@mazulo, seria interessante adicionar um material básico de Python - tipo os vídeos do [Ignorância Zero](https://www.youtube.com/playlist?list=PLfCKf0-awunOu2WyLe2pSD2fXUo795xRe) - para dar uma boa base ante de pegar Django?

**Comment by mazulo** [comment]
Sim, com certeza! Os vídeos desse canal parecem ser massa. Vamos adicionando aqui nesta issue material assim, aí quando já tiver um bom material, dá pra organizar numa ordem "evolutiva" e jogar na grade.
