### ISSUE TITLE
Vídeos dos encontros

### ISSUE THREAD

**Issue by delete** [mazulo/django_groups_-_initial_steps#7]
Ô @mazulo, não vai adicionar os [vídeos](https://www.youtube.com/playlist?list=PLX3H5HWvzsQtOIEWUcEzzkJNIF7IYMLIl) dos encontros aqui no repositório?

**Comment by mazulo** [comment]
Acredita que eu tava esquecendo completamente? hahahahah vou adicionar a notie (mas se quiser pode mandar um PR maroto :P)

**Comment by delete** [comment]
Done! Fechando aqui. :]
